# Generated by Django 4.1.6 on 2023-02-08 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyecto',
            new_name='Blog',
        ),
    ]
